#!/usr/bin/env node
/**
 * add-project.mjs
 * ---------------------------------------------------------------------------
 * 交互式添加「首页精选项目」，包含中英文，自动更新：
 *   - src/content/projects.json   （权威数据）
 *   - src/content/projects.ts     （由本脚本重新生成，供应用引入）
 *
 * 用法：
 *   node scripts/add-project.mjs
 *   npm run project:add
 *
 * 提示：
 *   - 分类 category 建议使用已在 src/locales 中存在的键，例如：
 *     frontend / css / buildTools / performance / practicalProjects / learningNotes / other
 *   - 标签用英文逗号分隔，例如：React, 前端, H5
 * ---------------------------------------------------------------------------
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import readline from 'node:readline/promises';
import { stdin, stdout } from 'node:process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..', '..');
const jsonFile = path.join(root, 'src', 'content', 'projects.json');
const tsFile = path.join(root, 'src', 'content', 'projects.ts');

const rl = readline.createInterface({ input: stdin, output: stdout });

async function ask(question, def = '') {
  const answer = (await rl.question(`${question}${def ? ` (${def})` : ''}: `)).trim();
  return answer || def;
}

function parseTags(input) {
  return input
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
}

async function main() {
  let projects = [];
  if (fs.existsSync(jsonFile)) {
    try {
      projects = JSON.parse(fs.readFileSync(jsonFile, 'utf-8'));
    } catch {
      projects = [];
    }
  }

  console.log('\n📝 添加新的精选项目（中英文）\n');

  const titleZh = await ask('项目中文名');
  const titleEn = await ask('项目英文名');
  const summaryZh = await ask('中文简介');
  const summaryEn = await ask('英文简介');
  const date = await ask('发布日期 (YYYY-MM-DD)', new Date().toISOString().slice(0, 10));
  const category = await ask('分类键 (frontend/css/buildTools/performance/practicalProjects/learningNotes/other)', 'practicalProjects');
  const readTime = await ask('阅读分钟数', '10');
  const tagsZh = await ask('中文标签 (逗号分隔)', '项目');
  const tagsEn = await ask('英文标签 (逗号分隔)', 'Project');

  // 先询问是否有部署链接
  const deployed = await ask('是否已有部署链接？（y/n）', 'n');
  const hasDeploy = deployed.toLowerCase() === 'y' || deployed.toLowerCase() === 'yes';

  let path1 = '';
  let path2 = '';

  if (hasDeploy) {
    path1 = await ask('部署链接 (https://...)', '');
    path2 = await ask('GitHub 仓库链接 (https://...)', '');
  } else {
    path1 = await ask('GitHub 仓库链接 (https://...)', '');
  }

  if (!titleZh || !titleEn) {
    console.error('❌ 项目名不能为空');
    rl.close();
    return;
  }

  const maxId = projects.reduce((m, p) => Math.max(m, Number(p.id) || 0), 0);
  const newId = maxId + 1;

  const project = {
    id: newId,
    type: 'project',
    path: path1,
    path2: path2 || undefined,
    title: { zh: titleZh, en: titleEn },
    summary: { zh: summaryZh, en: summaryEn },
    date,
    category,
    readTime: Number(readTime) || 10,
    tags: { zh: parseTags(tagsZh), en: parseTags(tagsEn) },
  };

  projects.push(project);
  fs.writeFileSync(jsonFile, JSON.stringify(projects, null, 2) + '\n', 'utf-8');

  const ts =
    `// AUTO-GENERATED by scripts/add-project.mjs — DO NOT EDIT BY HAND.\n` +
    `// 项目数据来源：src/content/projects.json\n` +
    `import type { ContentItem } from '@/components/ArticleList';\n\n` +
    `export const projectItems: ContentItem[] = ${JSON.stringify(projects, null, 2)};\n`;
  fs.writeFileSync(tsFile, ts, 'utf-8');

  console.log(`\n✅ 已添加项目 #${newId}「${titleZh}」`);
  console.log(`   - ${path.relative(root, jsonFile)}`);
  console.log(`   - ${path.relative(root, tsFile)}`);
  console.log('   运行 `npm run dev` 查看效果。\n');

  rl.close();
}

main().catch((err) => {
  console.error(err);
  rl.close();
  process.exit(1);
});
