// AUTO-GENERATED by scripts/add-blog.mjs — DO NOT EDIT BY HAND.
// 博客数据由 blogs/*.md 自动解析生成。
import type { ContentItem } from '@/components/ArticleList';

export const blogItems: ContentItem[] = [
  {
    "id": 1001,
    "type": "article",
    "path": "/article/1001",
    "title": {
      "zh": "使用 React 实现一个可命令式调用的弹窗",
      "en": "Building an Imperatively Callable Modal with React"
    },
    "summary": {
      "zh": "从 visible 状态到 useImperativeHandle，梳理几种弹窗实现方式",
      "en": "From visible state to useImperativeHandle, comparing several modal implementations"
    },
    "date": "2026-07-26",
    "category": "frontend",
    "readTime": 12,
    "tags": {
      "zh": [
        "React",
        "H5",
        "前端"
      ],
      "en": [
        "React",
        "H5",
        "Frontend"
      ]
    },
    "slug": "react-imperative-modal",
    "body": {
      "zh": "# 引言\r\n\r\n在日常 H5 开发中，弹窗是很常见的需求。本文对比几种实现方式，并重点介绍如何用 `useImperativeHandle` 做「命令式调用」。\r\n\r\n## 基础实现：受控 visible\r\n\r\n最直观的做法是用 `useState` 控制显隐：\r\n\r\n```tsx\r\nconst [visible, setVisible] = useState(false);\r\n```\r\n\r\n父组件通过 `setVisible(true)` 打开弹窗。缺点是需要把状态层层透传。\r\n\r\n## 命令式调用：useImperativeHandle\r\n\r\n把弹窗封装成命令式 API，通过 `ref` 暴露 `open` / `close`：\r\n\r\n```tsx\r\nuseImperativeHandle(ref, () => ({\r\n  open: () => setVisible(true),\r\n  close: () => setVisible(false),\r\n}));\r\n```\r\n\r\n> 提示：本文为示例内容，由 `add-blog` 脚本解析生成，用于验证 Markdown 渲染效果。\r\n\r\n## 小结\r\n\r\n- 受控方式适合简单场景；\r\n- 命令式方式适合在任意位置快速唤起弹窗。\r\n\r\n祝你编码愉快！",
      "en": "# 引言\r\n\r\n在日常 H5 开发中，弹窗是很常见的需求。本文对比几种实现方式，并重点介绍如何用 `useImperativeHandle` 做「命令式调用」。\r\n\r\n## 基础实现：受控 visible\r\n\r\n最直观的做法是用 `useState` 控制显隐：\r\n\r\n```tsx\r\nconst [visible, setVisible] = useState(false);\r\n```\r\n\r\n父组件通过 `setVisible(true)` 打开弹窗。缺点是需要把状态层层透传。\r\n\r\n## 命令式调用：useImperativeHandle\r\n\r\n把弹窗封装成命令式 API，通过 `ref` 暴露 `open` / `close`：\r\n\r\n```tsx\r\nuseImperativeHandle(ref, () => ({\r\n  open: () => setVisible(true),\r\n  close: () => setVisible(false),\r\n}));\r\n```\r\n\r\n> 提示：本文为示例内容，由 `add-blog` 脚本解析生成，用于验证 Markdown 渲染效果。\r\n\r\n## 小结\r\n\r\n- 受控方式适合简单场景；\r\n- 命令式方式适合在任意位置快速唤起弹窗。\r\n\r\n祝你编码愉快！"
    }
  }
];
