// AUTO-GENERATED by scripts/add-project.mjs — DO NOT EDIT BY HAND.
// 项目数据来源：src/content/projects.json
import type { ContentItem } from '@/components/ArticleList';

export const projectItems: ContentItem[] = [
  {
    "id": 1,
    "type": "project",
    "path": "https://issssa.top",
    "path2": "https://github.com/duk-destiny/blog",
    "title": {
      "zh": "个人博客网站",
      "en": "Personal Blog Website"
    },
    "summary": {
      "zh": "基于react，tailwindcss的个人博客网站",
      "en": "Personal blog website built with React, tailwindcss"
    },
    "date": "2026-04-25",
    "category": "practicalProjects",
    "readTime": 10,
    "tags": {
      "zh": [
        "React",
        "前端",
        "个人博客"
      ],
      "en": [
        "React",
        "Frontend",
        "Personal Blog"
      ]
    }
  },
  {
    "id": 2,
    "type": "project",
    "path": "https://notes.issssa.top",
    "path2": "https://github.com/duk-destiny/personal-studynotes",
    "title": {
      "zh": "学习笔记站",
      "en": "Learning Notes"
    },
    "summary": {
      "zh": "算法/框架/工具等学习笔记记录",
      "en": "Learning notes for algorithms, frameworks, tools, etc. records"
    },
    "date": "2026-04-25",
    "category": "practicalProjects",
    "readTime": 10,
    "tags": {
      "zh": [
        "vue",
        "前端",
        "学习笔记站"
      ],
      "en": [
        "vue",
        "Frontend",
        "Personal Notes"
      ]
    }
  },
  {
    "id": 3,
    "type": "project",
    "path": "https://github.com/duk-destiny/practical-skills",
    "title": {
      "zh": "个人skills合集",
      "en": "practical-skills"
    },
    "summary": {
      "zh": "一个涵盖多应用场景的 AI Skills 集合",
      "en": "A collection of AI Skills covering multiple application scenarios"
    },
    "date": "2026-07-27",
    "category": "practicalProjects",
    "readTime": 10,
    "tags": {
      "zh": [
        "AI应用",
        "skills"
      ],
      "en": [
        "AI applications",
        "skills"
      ]
    }
  }
];
