// AUTO-GENERATED by scripts/add-project.mjs — DO NOT EDIT BY HAND.
// 项目数据来源：src/content/projects.json
import type { ContentItem } from '@/components/ArticleList';

export const projectItems: ContentItem[] = [
  {
    "id": 1,
    "type": "project",
    "path": "https://issssa.top",
    "path2": "https://github.com/duk-destiny/blog",
    "title": {
      "zh": "个人博客网站",
      "en": "Personal Blog Website"
    },
    "summary": {
      "zh": "基于react，tailwindcss的个人博客网站",
      "en": "Personal blog website built with React, tailwindcss"
    },
    "date": "2026-04-25",
    "category": "practicalProjects",
    "readTime": 10,
    "tags": {
      "zh": [
        "React",
        "前端",
        "个人博客"
      ],
      "en": [
        "React",
        "Frontend",
        "Personal Blog"
      ]
    }
  },
  {
    "id": 2,
    "type": "project",
    "path": "https://notes.issssa.top",
    "path2": "https://github.com/duk-destiny/personal-studynotes",
    "title": {
      "zh": "学习笔记站",
      "en": "Learning Notes"
    },
    "summary": {
      "zh": "算法/框架/工具等学习笔记记录",
      "en": "Learning notes for algorithms, frameworks, tools, etc. records"
    },
    "date": "2026-04-25",
    "category": "practicalProjects",
    "readTime": 10,
    "tags": {
      "zh": [
        "vue",
        "前端",
        "学习笔记站"
      ],
      "en": [
        "vue",
        "Frontend",
        "Personal Notes"
      ]
    }
  },
  {
    "id": 3,
    "type": "project",
    "path": "https://github.com/duk-destiny/practical-skills",
    "title": {
      "zh": "个人skills合集",
      "en": "practical-skills"
    },
    "summary": {
      "zh": "一个涵盖多应用场景的 AI Skills 集合",
      "en": "A collection of AI Skills covering multiple application scenarios"
    },
    "date": "2026-07-27",
    "category": "practicalProjects",
    "readTime": 10,
    "tags": {
      "zh": [
        "AI应用",
        "skills"
      ],
      "en": [
        "AI applications",
        "skills"
      ]
    }
  },
  {
    "id": 4,
    "type": "project",
    "path": "https://github.com/duk-destiny/Radeon-hackathon-2026-07",
    "title": {
      "zh": "办公助理",
      "en": "Office Agent"
    },
    "summary": {
      "zh": "在AMD芯片上开发的一个私密的、以证据为基础的办公助理。它可以导入项目参考文件和任务列表，检索项目范围证据，评估任务进度，并结合规则和本地适配完成的模型， 并生成可审计的报告捆绑包。",
      "en": "A private, evidence‑based office assistant developed on AMD chips. It can import project reference files and task lists, retrieve evidence for project scopes, assess task progress, leverage rules and locally adapted completed models, and generate auditable report bundles."
    },
    "date": "2026-08-01",
    "category": "practicalProjects",
    "readTime": 10,
    "tags": {
      "zh": [
        "黑客松",
        "AMD模型适配",
        "AI应用"
      ],
      "en": [
        "Hackathon",
        "AMD model adaptation",
        "AI applications"
      ]
    }
  },
  {
    "id": 5,
    "type": "project",
    "path": "https://github.com/duk-destiny/Smart-Construction-Site-Guardian",
    "title": {
      "zh": "智能施工工地守护者",
      "en": "Smart Construction Site · Construction safety intelligent system"
    },
    "summary": {
      "zh": "一套从「视觉感知 → 规范检索 → 风险定级 → 闭环处置 → 人工纠偏 → 复训回写」端到端打通的施工安全智能体，兼顾研判深度（多 Agent 协同、RAG 条款引用、证据链可追溯）与告警时效（实时链路首帧出警、规则驱动、无阻塞推理）",
      "en": "A construction safety intelligent system integrates end-to-end processes from \"visual perception → standard retrieval → risk grading → closed-loop handling→ manual correction → retraining and rewriting,\" balancing deep judgment(multi-agent collaboration, RAG clause citation, evidence chain traceability) and alert timeliness (real-time first-frame alert alert, rule-driven, non-blocking reasoning)."
    },
    "date": "2026-07-28",
    "category": "practicalProjects",
    "readTime": 20,
    "tags": {
      "zh": [
        "施工安全智能体",
        "多 Agent 编排",
        "RAG",
        "自训练YOLOv8‑ONNX",
        "离线部署"
      ],
      "en": [
        "Construction Safety Agent",
        "Multi‑Agent Orchestration",
        "Retrieval‑Augmented Generation",
        "Self‑trained YOLOv8‑ONNX",
        "Offline Deployment"
      ]
    }
  },
  {
    "id": 6,
    "type": "project",
    "path": "https://github.com/duk-destiny/RAG-Medical-Assistant",
    "title": {
      "zh": "RAG 医疗助手",
      "en": "RAG Medical Assistant"
    },
    "summary": {
      "zh": "基于 LangGraph 的治理型医疗问答智能体：混合检索（向量 + BM25）、知识图谱多跳推理、 三层记忆体系（短期上下文 / 向量事件记忆 / 结构化画像）、角色隔离的健康档案访问控制。",
      "en": "Governance‑oriented Medical Question‑answering Agent Based on LangGraph: Hybrid Retrieval (Vector + BM25), Multi‑hop Reasoning on Knowledge Graphs, Three‑tier Memory System (Short‑term Context / Vector‑based Event Memory / Structured Profile), Role‑isolated Access Control for Health Records."
    },
    "date": "2026-07-15",
    "category": "practicalProjects",
    "readTime": 10,
    "tags": {
      "zh": [
        "RAG",
        "知识图谱",
        "AI 应用",
        "多层记忆",
        "Prompt 自优化"
      ],
      "en": [
        "RAG",
        "Knowledge Graph",
        "AI Applications",
        "Multi‑layer Memory",
        "Prompt Self‑optimization"
      ]
    }
  }
];
