#!/usr/bin/env node
/**
 * add-blog.mjs
 * ---------------------------------------------------------------------------
 * 解析 blogs/ 目录下的 Markdown 文件，自动生成 src/content/blogs.ts
 *
 * 用法：
 *   node scripts/add-blog/add-blog.mjs
 *   npm run blog:add
 *
 * 每个 .md 文件需包含 YAML frontmatter：
 *   ---
 *   title:
 *     zh: 中文标题
 *     en: English Title
 *   summary:
 *     zh: 中文摘要
 *     en: English summary
 *   date: 2026-07-26          # 发布日期 YYYY-MM-DD
 *   category: frontend        # 分类键，需存在于 src/locales 中
 *   readTime: 12              # 可选，预计阅读分钟数
 *   tags:
 *     zh: [React, 前端]
 *     en: [React, Frontend]
 *   slug: my-article-slug     # 可选，默认取文件名（不含 .md）
 *   body:                     # 可选，英文正文；省略则英文复用中文正文
 *     en: |
 *       English markdown body...
 *   ---
 * 正文 Markdown（作为「中文正文」）
 *
 * 注意：
 *   - 以 _ 开头的 .md 文件会被忽略（可用作模板，见 blogs/_template.md）
 *   - 生成结果写入 src/content/blogs.ts，请勿手动编辑该文件
 * ---------------------------------------------------------------------------
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { load as yamlLoad } from 'js-yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..', '..');
const blogsDir = path.join(root, 'blogs');
const outFile = path.join(root, 'src', 'content', 'blogs.ts');

function ensureDir(d) {
  fs.mkdirSync(d, { recursive: true });
}

function parseFrontmatter(text) {
  const m = text.match(/^---\s*\r?\n([\s\S]*?)\r?\n---\s*\r?\n?([\s\S]*)$/);
  if (!m) return { data: {}, body: text };
  const data = yamlLoad(m[1]) || {};
  return { data, body: m[2] };
}

function asBilingual(field) {
  if (field == null) return { zh: '', en: '' };
  if (typeof field === 'string') return { zh: field, en: field };
  return { zh: field.zh ?? '', en: field.en ?? field.zh ?? '' };
}

function asBilingualTags(field) {
  if (!field) return { zh: [], en: [] };
  if (Array.isArray(field)) return { zh: field, en: field };
  return {
    zh: Array.isArray(field.zh) ? field.zh : [],
    en: Array.isArray(field.en)
      ? field.en
      : Array.isArray(field.zh)
        ? field.zh
        : [],
  };
}

function main() {
  ensureDir(blogsDir);
  ensureDir(path.dirname(outFile));

  const files = fs
    .readdirSync(blogsDir)
    .filter((f) => f.endsWith('.md') && !f.startsWith('_'))
    .sort();

  const items = [];

  for (const file of files) {
    const raw = fs.readFileSync(path.join(blogsDir, file), 'utf-8');
    const { data, body } = parseFrontmatter(raw);
    const slug = String(data.slug || file.replace(/\.md$/i, ''));
    const title = asBilingual(data.title);
    const summary = asBilingual(data.summary);
    const tags = asBilingualTags(data.tags);

    const zhBody = typeof data.body?.zh === 'string' ? data.body.zh : body;
    const enBody =
      typeof data.body?.en === 'string'
        ? data.body.en
        : typeof data.body?.zh === 'string'
          ? data.body.zh
          : body;

    if (!title.zh || !title.en) {
      console.warn(`⚠️  跳过 ${file}：缺少 title.zh 或 title.en`);
      continue;
    }

    items.push({
      slug,
      title,
      summary,
      date: data.date || '1970-01-01',
      category: data.category || 'other',
      readTime: Number(data.readTime) || 10,
      tags,
      body: { zh: zhBody.trim(), en: enBody.trim() },
    });
  }

  // 按日期倒序，最新文章在前
  items.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));

  const contentItems = items.map((it, i) => {
    const id = 1000 + i + 1;
    return {
      id,
      type: 'article',
      path: `/article/${id}`,
      title: it.title,
      summary: it.summary,
      date: it.date,
      category: it.category,
      readTime: it.readTime,
      tags: it.tags,
      slug: it.slug,
      body: it.body,
    };
  });

  const ts =
    `// AUTO-GENERATED by scripts/add-blog.mjs — DO NOT EDIT BY HAND.\n` +
    `// 博客数据由 blogs/*.md 自动解析生成。\n` +
    `import type { ContentItem } from '@/components/ArticleList';\n\n` +
    `export const blogItems: ContentItem[] = ${JSON.stringify(contentItems, null, 2)};\n`;

  fs.writeFileSync(outFile, ts, 'utf-8');
  console.log(
    `✅ 已生成 ${path.relative(root, outFile)}，共 ${contentItems.length} 篇博客`
  );
}

main();
